apiVersion: v1
description: Fluentd Aggregator 헬름 차트는 로그 전달자로부터 지속적으로 이벤트를 수신함.
icon: https://www.fluentd.org/assets/img/miscellany/fluentd-logo.png
name: fluentd-aggregator
version: 0.3.0
appVersion: v2.3.1
home: https://www.fluentd.org/
sources:
- https://www.fluentd.org/
maintainers:
- name: guangbochen
  email: support@rancher.com
