apiVersion: v1
description: Apache Hadoop 소프트웨어 라이브러리는 간단한 프로그래밍 모델을 사용하여 컴퓨터 클러스터 전체에 대규모 데이터 세트를 분산처리 할 수있는 프레임워크임.
name: hadoop
version: 1.0.7
appVersion: 2.7.3
home: https://hadoop.apache.org/
sources:
- https://github.com/apache/hadoop
icon: http://hadoop.apache.org/images/hadoop-logo.jpg
maintainers:
- name: danisla
  email: disla@google.com
